apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
